services:
  app:
    build: .
    restart: always
    ports:
      - 4000:4000
    volumes:
      - package_store:./unpub-packages
    environment:
      - UNPUB_DB_HOST=db
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    volumes:
      - meta_store:/data/db
volumes:
  meta_store:
  package_store:
