name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information. Fork from https://github.com/bytedance/unpub
version: 1.0.0
homepage: https://github.com/watafactory/unpub
environment:
  sdk: ">=2.17.0 <3.0.0"
executables:
  unpub: unpub
dependencies:
  args: ^2.3.1
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  http_parser: ^4.0.1
  http: ^0.13.4
  archive: ^3.3.0
  logging: ^1.0.2
  meta: ^1.8.0
  googleapis: ^9.1.0
  yaml: ^3.1.1
  pub_semver: ^2.1.1
  json_annotation: ^4.5.0
  mongo_dart: ^0.7.4+1
  mime: ^1.0.2
  intl: ^0.17.0
  path: ^1.8.2
  collection: ^1.16.0
  shelf_cors_headers: ^0.1.3
dev_dependencies:
  test: ^1.21.3
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  shelf_router_generator: ^1.0.3
  chunked_stream: ^1.4.1
